//AUTHENTICATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNOUT = "SIGNOUT";

//SPECTACLES
export const ADD_SPECTACLE_SUCCESS = "ADD_SPECTACLE_SUCCESS";
export const ADD_SPECTACLE_ERROR = "ADD_SPECTACLE_ERROR";
export const GET_SPECTACLES_SUCCESS = "GET_SPECTACLES_SUCCESS";
export const GET_SPECTACLES_ERROR = "GET_SPECTACLES_ERROR";

//GENRES
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_ERROR = "GET_GENRES_ERROR";

export const FAVOURITE_CARD_SUCCESS = "FAVOURITE_CARD_SUCCESS";
export const FAVOURITE_CARD_ERROR = "FAVOURITE_CARD_ERROR";
